# contraints file (.xdc file) for lab 4
# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
# UNCOMMENT the below lines to generate a virtual clock required for timing # analysis
create_clock -add -name sys_clk_pin -period 12.00 -waveform {0 6} [get_ports clk]
set_input_delay -clock [get_clocks sys_clk_pin] -add_delay 0.000 [get_ports -filter { NAME =~ "*" && DIRECTION == "IN" } ]
set_output_delay -clock [get_clocks sys_clk_pin] -add_delay 0.000 [get_ports -filter { NAME =~ "*" && DIRECTION == "OUT" } ]
# leds
# above is for post implementation timing simulation and timing reports
set_property PACKAGE_PIN U16 [get_ports {LEDs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN E19 [get_ports {LEDs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U19 [get_ports {LEDs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN V19 [get_ports {LEDs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN W18 [get_ports {LEDs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN U15 [get_ports {q[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q[5]}]
set_property PACKAGE_PIN U14 [get_ports {q[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q[6]}]
set_property PACKAGE_PIN V14 [get_ports {q[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q[7]}]
# LEDs for Debugging purposes
set_property PACKAGE_PIN V13 [get_ports {db[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {db[0]}]
set_property PACKAGE_PIN V3 [get_ports {db[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {db[1]}]
set_property PACKAGE_PIN W3 [get_ports {db[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {db[2]}]
set_property PACKAGE_PIN U3 [get_ports {db[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {db[3]}]
set_property PACKAGE_PIN P3 [get_ports {db[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {db[4]}]
set_property PACKAGE_PIN N3 [get_ports {db[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {db[5]}]
set_property PACKAGE_PIN P1 [get_ports {db[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {db[6]}]
set_property PACKAGE_PIN L1 [get_ports {db[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {db[7]}]
#Buttons
set_property PACKAGE_PIN U18 [get_ports next_inst]
set_property IOSTANDARD LVCMOS33 [get_ports next_inst]
set_property PACKAGE_PIN W19 [get_ports roll]
set_property IOSTANDARD LVCMOS33 [get_ports roll]
#Switches
set_property PACKAGE_PIN V17 [get_ports {switch[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]
set_property PACKAGE_PIN V16 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property PACKAGE_PIN W16 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property PACKAGE_PIN W17 [get_ports {switch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
set_property PACKAGE_PIN W15 [get_ports {switch[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
set_property PACKAGE_PIN V15 [get_ports {switch[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[5]}]
set_property PACKAGE_PIN W14 [get_ports {switch[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[6]}]
set_property PACKAGE_PIN W13 [get_ports {switch[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[7]}]
#State Switches
set_property PACKAGE_PIN U1 [get_ports {BNT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BNT[0]}]
set_property PACKAGE_PIN T1 [get_ports {BNT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BNT[1]}]
set_property PACKAGE_PIN R2 [get_ports {BNT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BNT[2]}]
#7-Segment
#Anodes
set_property PACKAGE_PIN U2 [get_ports {Anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {Anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {Anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {Anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[3]}]
#Cathodes
set_property PACKAGE_PIN W7 [get_ports {Cathode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathode[7]}]
set_property PACKAGE_PIN W6 [get_ports {Cathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathode[6]}]
set_property PACKAGE_PIN U8 [get_ports {Cathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathode[5]}]
set_property PACKAGE_PIN V8 [get_ports {Cathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathode[4]}]
set_property PACKAGE_PIN U5 [get_ports {Cathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathode[3]}]
set_property PACKAGE_PIN V5 [get_ports {Cathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathode[2]}]
set_property PACKAGE_PIN U7 [get_ports {Cathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathode[1]}]
set_property PACKAGE_PIN V7 [get_ports {Cathode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathode[0]}]
